# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(794, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.lr_video_widget = QVideoWidget(self.centralwidget)
        self.lr_video_widget.setObjectName("lr_video_widget")
        self.gridLayout.addWidget(self.lr_video_widget, 3, 0, 1, 5)
        self.sr_video_widget = QVideoWidget(self.centralwidget)
        self.sr_video_widget.setObjectName("sr_video_widget")
        self.gridLayout.addWidget(self.sr_video_widget, 5, 0, 1, 5)
        self.info_label = QtWidgets.QLabel(self.centralwidget)
        self.info_label.setObjectName("info_label")
        self.gridLayout.addWidget(self.info_label, 0, 4, 1, 1)
        self.confirm_btn = QtWidgets.QPushButton(self.centralwidget)
        self.confirm_btn.setObjectName("confirm_btn")
        self.gridLayout.addWidget(self.confirm_btn, 1, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 1, 4, 1, 1)
        self.max_seq_len_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.max_seq_len_lineEdit.setObjectName("max_seq_len_lineEdit")
        self.gridLayout.addWidget(self.max_seq_len_lineEdit, 1, 1, 1, 1)
        self.fps_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.fps_lineEdit.setObjectName("fps_lineEdit")
        self.gridLayout.addWidget(self.fps_lineEdit, 0, 1, 1, 1)
        self.select_btn = QtWidgets.QPushButton(self.centralwidget)
        self.select_btn.setObjectName("select_btn")
        self.gridLayout.addWidget(self.select_btn, 0, 0, 1, 1)
        self.cpu_radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.cpu_radioButton.setChecked(False)
        self.cpu_radioButton.setObjectName("cpu_radioButton")
        self.gridLayout.addWidget(self.cpu_radioButton, 1, 2, 1, 1)
        self.gpu_radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.gpu_radioButton.setChecked(True)
        self.gpu_radioButton.setObjectName("gpu_radioButton")
        self.gridLayout.addWidget(self.gpu_radioButton, 0, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 794, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.info_label.setText(_translate("MainWindow", "TextLabel"))
        self.confirm_btn.setText(_translate("MainWindow", "确认"))
        self.select_btn.setText(_translate("MainWindow", "选择文件"))
        self.cpu_radioButton.setText(_translate("MainWindow", "CPU"))
        self.gpu_radioButton.setText(_translate("MainWindow", "GPU"))
from PyQt5.QtMultimediaWidgets import QVideoWidget
